<a href="https://colab.research.google.com/github/Swastika-Roy/Python-concepts/blob/main/dataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Data_Large.csv')
df.describe()

,order_id,quantity,unit_price,total_amount,discount_percent,profit
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,1100.500000,3.105000,120.810000,143.623950,7.690000,28.691000
std,57.879185,3.583039,157.424362,149.702091,6.097524,29.855271
min,1001.000000,1.000000,1.990000,17.970000,0.000000,3.590000
25%,1050.750000,1.000000,14.740000,44.985000,0.000000,8.990000
50%,1100.500000,1.000000,59.990000,79.980000,8.000000,15.990000
75%,1150.250000,4.000000,159.990000,189.990000,12.000000,37.990000
max,1200.000000,20.000000,899.990000,899.990000,20.000000,179.990000

BASIC SELECTION **OPERATION**

In [ ]:
df.head(10) #first 10

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
6,1007,C006,Frank Miller,Desk Lamp,Furniture,Lighting,2,39.99,79.98,10,...,2023-01-24,Standard,West,Washington,Seattle,Home Office,PayPal,15.99,Online,False
7,1008,C007,Grace Lee,Printer Ink,Office Supplies,Printing,4,29.99,119.96,5,...,2023-01-25,Standard,Central,Ohio,Columbus,Consumer,Credit Card,23.99,Store,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
9,1010,C009,Isabel Martinez,Bookshelf,Furniture,Storage,1,189.99,189.99,8,...,2023-01-28,Standard,East,Pennsylvania,Philadelphia,Home Office,Debit Card,37.99,Store,False

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Data_Large.csv')
print(df[df['order_id'].isin([1001,1050,1100,1150,1200])])

     order_id customer_id   customer_name    product_name     category  \
0        1001        C001  Alice Williams          Laptop  Electronics
49       1050        C042  Quincy Stewart   Graphics Card  Electronics
99       1100        C089       Leo Hayes  Graphic Tablet  Electronics
149      1150        C134     Elle Barton        Armchair    Furniture
199      1200        C180       Yara Love  Umbrella Stand    Furniture

    sub_category  quantity  unit_price  total_amount  discount_percent  ...  \
0      Computers         1      899.99        899.99                10  ...
49     Computers         1      399.99        399.99                15  ...
99   Accessories         1      159.99        159.99                15  ...
149      Seating         1      349.99        349.99                15  ...
199  Accessories         1       29.99         29.99                 5  ...

      ship_date ship_mode region         state          city customer_segment  \
0    2023-01-18   Express   East      New York      New York         Consumer
49   2023-03-08   Express   East  Rhode Island    Providence         Consumer
99   2023-04-27   Express  South         Texas        Dallas         Consumer
149  2023-06-17  Standard   West        Oregon         Salem         Consumer
199  2023-08-05  Standard  South     Tennessee  Murfreesboro      Home Office

    payment_method  profit  sales_channel returned
0      Credit Card  179.99         Online    False
49      Debit Card   79.99         Online    False
99      Debit Card   31.99         Online    False
149     Debit Card   69.99          Store    False
199    Credit Card    5.99          Store    False

[5 rows x 21 columns]

In [ ]:
#last 5
df.tail(5)

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

In [ ]:
#specific col
# df['customer_name']
df[['customer_name','customer_id']]

      customer_name customer_id
0    Alice Williams        C001
1       Bob Johnson        C002
2       Carol Smith        C003
3       David Brown        C004
4       Bob Johnson        C002
..              ...         ...
195       Umar Shaw        C176
196       Vale Horn        C177
197       Wade Hull        C178
198       Xena Pace        C179
199       Yara Love        C180

[200 rows x 2 columns]

In [ ]:
#select rows by index
df.iloc[0]

order_id                      1001
customer_id                   C001
customer_name       Alice Williams
product_name                Laptop
category               Electronics
sub_category             Computers
quantity                         1
unit_price                  899.99
total_amount                899.99
discount_percent                10
order_date              2023-01-15
ship_date               2023-01-18
ship_mode                  Express
region                        East
state                     New York
city                      New York
customer_segment          Consumer
payment_method         Credit Card
profit                      179.99
sales_channel               Online
returned                     False
Name: 0, dtype: object

In [ ]:
#select rows by order_id column value
df['order_id']

0      1001
1      1002
2      1003
3      1004
4      1005
       ...
195    1196
196    1197
197    1198
198    1199
199    1200
Name: order_id, Length: 200, dtype: int64

In [ ]:
#oders from electronic category
df.loc[df['category']=='Electronics']

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
10,1011,C010,Jack Anderson,Keyboard Mechanical,Electronics,Accessories,2,89.99,179.98,10,...,2023-01-27,Express,West,Oregon,Portland,Consumer,PayPal,35.99,Online,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,1187,C168,Myra Case,Doorbell Camera,Electronics,Security,1,149.99,149.99,15,...,2023-07-23,Express,South,Texas,Corpus Christi,Consumer,PayPal,29.99,Online,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False

In [ ]:
#orders with total amount greater than $300
df.loc[df['total_amount']>300]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
12,1013,C011,Kate Wilson,Tablet 10inch,Electronics,Mobile,1,399.99,399.99,15,...,2023-01-30,Express,Central,Michigan,Detroit,Corporate,Credit Card,79.99,Online,False
22,1023,C020,Tina Walker,Conference Table,Furniture,Tables,1,799.99,799.99,20,...,2023-02-10,Standard,South,Tennessee,Nashville,Corporate,Credit Card,159.99,Store,False
29,1030,C026,Zack Wright,Sofa,Furniture,Seating,1,599.99,599.99,15,...,2023-02-17,Standard,Central,Missouri,Kansas City,Consumer,Debit Card,119.99,Store,False
38,1039,C033,Hannah Perez,Corner Desk,Furniture,Desks,1,349.99,349.99,12,...,2023-02-26,Standard,Central,Kansas,Wichita,Home Office,PayPal,69.99,Online,False
40,1041,C035,Julia Turner,Projector,Electronics,Presentation,1,499.99,499.99,20,...,2023-02-28,Express,West,Montana,Billings,Corporate,Credit Card,99.99,Online,True
49,1050,C042,Quincy Stewart,Graphics Card,Electronics,Computers,1,399.99,399.99,15,...,2023-03-08,Express,East,Rhode Island,Providence,Consumer,Debit Card,79.99,Online,False
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
72,1073,C063,Lisa Kelly,L-Shaped Desk,Furniture,Desks,1,499.99,499.99,15,...,2023-04-01,Standard,West,California,San Diego,Consumer,Credit Card,99.99,Store,False
87,1088,C077,Zane Hughes,Gaming Chair,Furniture,Chairs,1,349.99,349.99,18,...,2023-04-16,Standard,Central,Minnesota,St. Paul,Consumer,Debit Card,69.99,Online,False
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True
101,1102,C090,Mona Myers,Reception Desk,Furniture,Desks,1,699.99,699.99,20,...,2023-05-01,Standard,West,Washington,Tacoma,Corporate,PayPal,139.99,Store,False
103,1104,C092,Opal Wells,Drone Camera,Electronics,Photography,1,599.99,599.99,18,...,2023-05-02,Express,East,Virginia,Chesapeake,Consumer,Credit Card,119.99,Online,False
109,1110,C098,Uma Ferguson,Drafting Table,Furniture,Desks,1,399.99,399.99,15,...,2023-05-08,Standard,West,Nevada,Reno,Home Office,Credit Card,79.99,Store,False
121,1122,C109,Faye Castillo,Recliner,Furniture,Seating,1,449.99,449.99,20,...,2023-05-20,Standard,South,Louisiana,Shreveport,Consumer,Credit Card,89.99,Store,False
149,1150,C134,Elle Barton,Armchair,Furniture,Seating,1,349.99,349.99,15,...,2023-06-17,Standard,West,Oregon,Salem,Consumer,Debit Card,69.99,Store,False
159,1160,C143,Neil Goodman,Wardrobe,Furniture,Storage,1,399.99,399.99,18,...,2023-06-27,Standard,Central,Missouri,Columbia,Consumer,PayPal,79.99,Store,False
165,1166,C149,Troy Cruz,Dining Chair,Furniture,Chairs,4,79.99,319.96,15,...,2023-07-03,Standard,East,Pennsylvania,Harrisburg,Consumer,PayPal,63.99,Store,False
177,1178,C160,Ella Pugh,Bed Frame,Furniture,Bedroom,1,349.99,349.99,18,...,2023-07-15,Standard,South,Florida,Port St. Lucie,Consumer,Credit Card,69.99,Store,False

In [ ]:
df.loc[df['discount_percent']>15]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
22,1023,C020,Tina Walker,Conference Table,Furniture,Tables,1,799.99,799.99,20,...,2023-02-10,Standard,South,Tennessee,Nashville,Corporate,Credit Card,159.99,Store,False
40,1041,C035,Julia Turner,Projector,Electronics,Presentation,1,499.99,499.99,20,...,2023-02-28,Express,West,Montana,Billings,Corporate,Credit Card,99.99,Online,True
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
87,1088,C077,Zane Hughes,Gaming Chair,Furniture,Chairs,1,349.99,349.99,18,...,2023-04-16,Standard,Central,Minnesota,St. Paul,Consumer,Debit Card,69.99,Online,False
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True
101,1102,C090,Mona Myers,Reception Desk,Furniture,Desks,1,699.99,699.99,20,...,2023-05-01,Standard,West,Washington,Tacoma,Corporate,PayPal,139.99,Store,False
103,1104,C092,Opal Wells,Drone Camera,Electronics,Photography,1,599.99,599.99,18,...,2023-05-02,Express,East,Virginia,Chesapeake,Consumer,Credit Card,119.99,Online,False
118,1119,C106,Cody Garza,Futon,Furniture,Seating,1,299.99,299.99,18,...,2023-05-17,Standard,Central,Minnesota,Rochester,Consumer,Credit Card,59.99,Store,False
121,1122,C109,Faye Castillo,Recliner,Furniture,Seating,1,449.99,449.99,20,...,2023-05-20,Standard,South,Louisiana,Shreveport,Consumer,Credit Card,89.99,Store,False
142,1143,C128,Yale Snow,Video Doorbell,Electronics,Security,1,199.99,199.99,18,...,2023-06-09,Express,Central,Illinois,Joliet,Consumer,Credit Card,39.99,Online,False
159,1160,C143,Neil Goodman,Wardrobe,Furniture,Storage,1,399.99,399.99,18,...,2023-06-27,Standard,Central,Missouri,Columbia,Consumer,PayPal,79.99,Store,False
177,1178,C160,Ella Pugh,Bed Frame,Furniture,Bedroom,1,349.99,349.99,18,...,2023-07-15,Standard,South,Florida,Port St. Lucie,Consumer,Credit Card,69.99,Store,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False

In [ ]:
#online orders only
df.loc[df['sales_channel']=='Online']

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
6,1007,C006,Frank Miller,Desk Lamp,Furniture,Lighting,2,39.99,79.98,10,...,2023-01-24,Standard,West,Washington,Seattle,Home Office,PayPal,15.99,Online,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,1187,C168,Myra Case,Doorbell Camera,Electronics,Security,1,149.99,149.99,15,...,2023-07-23,Express,South,Texas,Corpus Christi,Consumer,PayPal,29.99,Online,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False

In [ ]:
#returned items
df.loc[df['returned']==True]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
40,1041,C035,Julia Turner,Projector,Electronics,Presentation,1,499.99,499.99,20,...,2023-02-28,Express,West,Montana,Billings,Corporate,Credit Card,99.99,Online,True
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True

In [ ]:
df.loc[(df['category']=='Electronics') & (df['total_amount']>200)]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
12,1013,C011,Kate Wilson,Tablet 10inch,Electronics,Mobile,1,399.99,399.99,15,...,2023-01-30,Express,Central,Michigan,Detroit,Corporate,Credit Card,79.99,Online,False
35,1036,C008,Henry Taylor,Smart Watch,Electronics,Wearables,1,299.99,299.99,15,...,2023-02-22,Express,South,Florida,Miami,Consumer,Credit Card,59.99,Online,False
40,1041,C035,Julia Turner,Projector,Electronics,Presentation,1,499.99,499.99,20,...,2023-02-28,Express,West,Montana,Billings,Corporate,Credit Card,99.99,Online,True
49,1050,C042,Quincy Stewart,Graphics Card,Electronics,Computers,1,399.99,399.99,15,...,2023-03-08,Express,East,Rhode Island,Providence,Consumer,Debit Card,79.99,Online,False
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
92,1093,C082,Ella Foster,Noise Cancelling Headphones,Electronics,Audio,1,249.99,249.99,15,...,2023-04-20,Express,South,Georgia,Columbus,Consumer,Credit Card,49.99,Online,False
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True
103,1104,C092,Opal Wells,Drone Camera,Electronics,Photography,1,599.99,599.99,18,...,2023-05-02,Express,East,Virginia,Chesapeake,Consumer,Credit Card,119.99,Online,False
106,1107,C095,Ricky Carroll,Action Camera,Electronics,Photography,1,279.99,279.99,15,...,2023-05-04,Express,Central,Illinois,Peoria,Consumer,Credit Card,55.99,Online,False
111,1112,C100,Wanda Medina,Security Camera,Electronics,Security,2,129.99,259.98,12,...,2023-05-09,Express,East,Pennsylvania,Erie,Consumer,PayPal,51.99,Online,False
126,1127,C113,Jade Bowman,Portable Printer,Electronics,Printing,1,249.99,249.99,12,...,2023-05-24,Express,Central,Illinois,Naperville,Consumer,PayPal,49.99,Online,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False

In [ ]:
#furniture or office supplies
df.loc[(df['category']=='Furniture') | (df['category']=='Office Supplies')]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
6,1007,C006,Frank Miller,Desk Lamp,Furniture,Lighting,2,39.99,79.98,10,...,2023-01-24,Standard,West,Washington,Seattle,Home Office,PayPal,15.99,Online,False
7,1008,C007,Grace Lee,Printer Ink,Office Supplies,Printing,4,29.99,119.96,5,...,2023-01-25,Standard,Central,Ohio,Columbus,Consumer,Credit Card,23.99,Store,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1194,C174,Sage Berg,Patio Chair,Furniture,Outdoor,2,69.99,139.98,15,...,2023-07-31,Standard,Central,Indiana,Carmel,Consumer,Credit Card,27.99,Store,False
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,2023-07-31,Standard,West,Washington,Renton,Home Office,Debit Card,8.37,Store,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

In [ ]:
#consumer segment with express shipping
df.loc[(df['customer_segment']=='Consumer') & (df['ship_mode']=='Express')]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
10,1011,C010,Jack Anderson,Keyboard Mechanical,Electronics,Accessories,2,89.99,179.98,10,...,2023-01-27,Express,West,Oregon,Portland,Consumer,PayPal,35.99,Online,False
15,1016,C014,Noah Rodriguez,Webcam HD,Electronics,Accessories,1,79.99,79.99,5,...,2023-02-02,Express,East,New Jersey,Newark,Consumer,Credit Card,15.99,Online,False
19,1020,C017,Quinn Harris,Laptop Bag,Electronics,Accessories,2,49.99,99.98,5,...,2023-02-06,Express,West,Colorado,Denver,Consumer,Debit Card,19.99,Online,False
21,1022,C019,Sam Lewis,Gaming Mouse,Electronics,Accessories,1,59.99,59.99,15,...,2023-02-08,Express,Central,Wisconsin,Milwaukee,Consumer,Credit Card,11.99,Online,False
23,1024,C005,Emma Davis,Headphones,Electronics,Accessories,1,129.99,129.99,10,...,2023-02-09,Express,East,Massachusetts,Boston,Consumer,PayPal,25.99,Online,False
28,1029,C025,Yara King,Ergonomic Keyboard,Electronics,Accessories,1,119.99,119.99,10,...,2023-02-15,Express,West,Utah,Salt Lake City,Consumer,Credit Card,23.99,Online,False
30,1031,C001,Alice Williams,External SSD,Electronics,Storage,1,149.99,149.99,8,...,2023-02-16,Express,East,New York,New York,Consumer,Credit Card,29.99,Online,False
35,1036,C008,Henry Taylor,Smart Watch,Electronics,Wearables,1,299.99,299.99,15,...,2023-02-22,Express,South,Florida,Miami,Consumer,Credit Card,59.99,Online,False
44,1045,C038,Mike Parker,Bluetooth Speaker,Electronics,Audio,1,79.99,79.99,10,...,2023-03-03,Express,South,Mississippi,Jackson,Consumer,PayPal,15.99,Online,False
49,1050,C042,Quincy Stewart,Graphics Card,Electronics,Computers,1,399.99,399.99,15,...,2023-03-08,Express,East,Rhode Island,Providence,Consumer,Debit Card,79.99,Online,False
53,1054,C046,Umar Reed,RAM 16GB,Electronics,Computers,2,79.99,159.98,10,...,2023-03-12,Express,East,Delaware,Wilmington,Consumer,PayPal,31.99,Online,False
58,1059,C005,Emma Davis,Wireless Charger,Electronics,Accessories,1,34.99,34.99,5,...,2023-03-17,Express,East,Massachusetts,Boston,Consumer,Credit Card,6.99,Online,False
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
69,1070,C008,Henry Taylor,Smart Speaker,Electronics,Audio,2,99.99,199.98,15,...,2023-03-28,Express,South,Florida,Tampa,Consumer,PayPal,39.99,Online,False
74,1075,C065,Nina Price,Gaming Headset,Electronics,Accessories,1,89.99,89.99,10,...,2023-04-02,Express,Central,Wisconsin,Madison,Consumer,Debit Card,17.99,Online,False
77,1078,C068,Quinn Barnes,SSD 1TB,Electronics,Storage,1,119.99,119.99,10,...,2023-04-05,Express,West,Colorado,Aurora,Consumer,Credit Card,23.99,Online,False
80,1081,C071,Tanya Coleman,Fitness Tracker,Electronics,Wearables,1,129.99,129.99,12,...,2023-04-08,Express,South,Florida,Orlando,Consumer,Credit Card,25.99,Online,False
82,1083,C073,Vicky Perry,Microphone USB,Electronics,Audio,1,69.99,69.99,10,...,2023-04-10,Express,Central,Missouri,St. Louis,Consumer,PayPal,13.99,Online,False
89,1090,C079,Ben Washington,Portable Monitor,Electronics,Computers,1,199.99,199.99,12,...,2023-04-17,Express,East,Pennsylvania,Allentown,Consumer,Credit Card,39.99,Online,False
92,1093,C082,Ella Foster,Noise Cancelling Headphones,Electronics,Audio,1,249.99,249.99,15,...,2023-04-20,Express,South,Georgia,Columbus,Consumer,Credit Card,49.99,Online,False
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True
97,1098,C087,Jake Griffin,Portable SSD,Electronics,Storage,1,179.99,179.99,12,...,2023-04-25,Express,West,Oregon,Eugene,Consumer,PayPal,35.99,Online,False
99,1100,C089,Leo Hayes,Graphic Tablet,Electronics,Accessories,1,159.99,159.99,15,...,2023-04-27,Express,South,Texas,Dallas,Consumer,Debit Card,31.99,Online,False
103,1104,C092,Opal Wells,Drone Camera,Electronics,Photography,1,599.99,599.99,18,...,2023-05-02,Express,East,Virginia,Chesapeake,Consumer,Credit Card,119.99,Online,False
106,1107,C095,Ricky Carroll,Action Camera,Electronics,Photography,1,279.99,279.99,15,...,2023-05-04,Express,Central,Illinois,Peoria,Consumer,Credit Card,55.99,Online,False
111,1112,C100,Wanda Medina,Security Camera,Electronics,Security,2,129.99,259.98,12,...,2023-05-09,Express,East,Pennsylvania,Erie,Consumer,PayPal,51.99,Online,False
117,1118,C105,Beth Ortiz,Smart Doorbell,Electronics,Security,1,149.99,149.99,15,...,2023-05-15,Express,South,Texas,San Antonio,Consumer,PayPal,29.99,Online,False
123,1124,C008,Henry Taylor,E-Reader,Electronics,Reading,1,139.99,139.99,10,...,2023-05-21,Express,South,Florida,Miami,Consumer,PayPal,27.99,Online,False
126,1127,C113,Jade Bowman,Portable Printer,Electronics,Printing,1,249.99,249.99,12,...,2023-05-24,Express,Central,Illinois,Naperville,Consumer,PayPal,49.99,Online,False
129,1130,C116,Mike Gross,Drawing Tablet,Electronics,Accessories,1,199.99,199.99,15,...,2023-05-27,Express,East,Pennsylvania,Reading,Consumer,PayPal,39.99,Online,False
135,1136,C122,Seth Austin,Smart Thermostat,Electronics,Home,1,199.99,199.99,15,...,2023-06-02,Express,South,Texas,Fort Worth,Consumer,PayPal,39.99,Online,False
137,1138,C005,Emma Davis,Air Purifier,Electronics,Home,1,149.99,149.99,10,...,2023-06-04,Express,East,Massachusetts,Boston,Consumer,Debit Card,29.99,Online,False
139,1140,C125,Vera Pena,Smart Lock,Electronics,Security,1,179.99,179.99,15,...,2023-06-06,Express,East,Virginia,Newport News,Consumer,Credit Card,35.99,Online,False
142,1143,C128,Yale Snow,Video Doorbell,Electronics,Security,1,199.99,199.99,18,...,2023-06-09,Express,Central,Illinois,Joliet,Consumer,Credit Card,39.99,Online,False
153,1154,C008,Henry Taylor,Fitness Band,Electronics,Wearables,1,79.99,79.99,8,...,2023-06-20,Express,South,Florida,Miami,Consumer,PayPal,15.99,Online,False
161,1162,C145,Pete Weeks,Backup Battery,Electronics,Accessories,1,89.99,89.99,12,...,2023-06-28,Express,East,New York,Albany,Consumer,Debit Card,17.99,Online,False
173,1174,C156,Alma Haas,Mini Fridge,Electronics,Home,1,199.99,199.99,12,...,2023-07-10,Express,South,Texas,Laredo,Consumer,Debit Card,39.99,Online,False
179,1180,C162,Gale Rich,Digital Frame,Electronics,Home,1,129.99,129.99,15,...,2023-07-16,Express,West,Nevada,Sparks,Consumer,Debit Card,25.99,Online,False
183,1184,C165,Jana Duke,Soundbar,Electronics,Audio,1,179.99,179.99,12,...,2023-07-20,Express,East,Pennsylvania,Lancaster,Consumer,PayPal,35.99,Online,False
186,1187,C168,Myra Case,Doorbell Camera,Electronics,Security,1,149.99,149.99,15,...,2023-07-23,Express,South,Texas,Corpus Christi,Consumer,PayPal,29.99,Online,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False

In [ ]:
#orders from east or west region with high value
df.loc[((df['region']=='East') | (df['region']=='West')) & (df['total_amount']>500)]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
101,1102,C090,Mona Myers,Reception Desk,Furniture,Desks,1,699.99,699.99,20,...,2023-05-01,Standard,West,Washington,Tacoma,Corporate,PayPal,139.99,Store,False
103,1104,C092,Opal Wells,Drone Camera,Electronics,Photography,1,599.99,599.99,18,...,2023-05-02,Express,East,Virginia,Chesapeake,Consumer,Credit Card,119.99,Online,False

In [ ]:
#online electronics with discount
df.loc[(df['sales_channel']=='Online') & (df['category']=='Electronics') & (df['discount_percent']>0)]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
10,1011,C010,Jack Anderson,Keyboard Mechanical,Electronics,Accessories,2,89.99,179.98,10,...,2023-01-27,Express,West,Oregon,Portland,Consumer,PayPal,35.99,Online,False
12,1013,C011,Kate Wilson,Tablet 10inch,Electronics,Mobile,1,399.99,399.99,15,...,2023-01-30,Express,Central,Michigan,Detroit,Corporate,Credit Card,79.99,Online,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,1187,C168,Myra Case,Doorbell Camera,Electronics,Security,1,149.99,149.99,15,...,2023-07-23,Express,South,Texas,Corpus Christi,Consumer,PayPal,29.99,Online,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False

**Range filtering**

In [ ]:
#orders between $100 and $300
import pandas as pd
df = pd.read_csv('/content/Data_Large.csv')
df.loc[(df['total_amount']>100) & (df['total_amount']<300)]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
7,1008,C007,Grace Lee,Printer Ink,Office Supplies,Printing,4,29.99,119.96,5,...,2023-01-25,Standard,Central,Ohio,Columbus,Consumer,Credit Card,23.99,Store,False
9,1010,C009,Isabel Martinez,Bookshelf,Furniture,Storage,1,189.99,189.99,8,...,2023-01-28,Standard,East,Pennsylvania,Philadelphia,Home Office,Debit Card,37.99,Store,False
10,1011,C010,Jack Anderson,Keyboard Mechanical,Electronics,Accessories,2,89.99,179.98,10,...,2023-01-27,Express,West,Oregon,Portland,Consumer,PayPal,35.99,Online,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,1187,C168,Myra Case,Doorbell Camera,Electronics,Security,1,149.99,149.99,15,...,2023-07-23,Express,South,Texas,Corpus Christi,Consumer,PayPal,29.99,Online,False
189,1190,C008,Henry Taylor,Robot Vacuum,Electronics,Home,1,299.99,299.99,20,...,2023-07-27,Express,South,Florida,Miami,Consumer,PayPal,59.99,Online,False
190,1191,C171,Paul Ware,Shelving Unit,Furniture,Storage,1,129.99,129.99,10,...,2023-07-28,Standard,West,California,Irvine,Consumer,Credit Card,25.99,Store,False
193,1194,C174,Sage Berg,Patio Chair,Furniture,Outdoor,2,69.99,139.98,15,...,2023-07-31,Standard,Central,Indiana,Carmel,Consumer,Credit Card,27.99,Store,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False

In [ ]:
#orders with 10-15%
df.loc[df.discount_percent.between(10,15)]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
6,1007,C006,Frank Miller,Desk Lamp,Furniture,Lighting,2,39.99,79.98,10,...,2023-01-24,Standard,West,Washington,Seattle,Home Office,PayPal,15.99,Online,False
8,1009,C008,Henry Taylor,Smartphone,Electronics,Mobile,1,699.99,699.99,12,...,2023-01-26,Express,South,Florida,Miami,Consumer,Credit Card,139.99,Online,False
10,1011,C010,Jack Anderson,Keyboard Mechanical,Electronics,Accessories,2,89.99,179.98,10,...,2023-01-27,Express,West,Oregon,Portland,Consumer,PayPal,35.99,Online,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1191,C171,Paul Ware,Shelving Unit,Furniture,Storage,1,129.99,129.99,10,...,2023-07-28,Standard,West,California,Irvine,Consumer,Credit Card,25.99,Store,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False
193,1194,C174,Sage Berg,Patio Chair,Furniture,Outdoor,2,69.99,139.98,15,...,2023-07-31,Standard,Central,Indiana,Carmel,Consumer,Credit Card,27.99,Store,False
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False

**string filterin**

In [ ]:
#products containing chair
df.loc[df['product_name'].str.contains('chair')]
# df.loc[df['product_name'].str.contains('chair')]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
149,1150,C134,Elle Barton,Armchair,Furniture,Seating,1,349.99,349.99,15,...,2023-06-17,Standard,West,Oregon,Salem,Consumer,Debit Card,69.99,Store,False

In [ ]:
#customer starting with 'A'
df.loc[df.customer_name.str.startswith('A')]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
11,1012,C001,Alice Williams,Paper Clips,Office Supplies,Organizers,10,2.99,29.90,0,...,2023-01-29,Standard,East,New York,New York,Consumer,Credit Card,8.97,Store,False
30,1031,C001,Alice Williams,External SSD,Electronics,Storage,1,149.99,149.99,8,...,2023-02-16,Express,East,New York,New York,Consumer,Credit Card,29.99,Online,False
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
85,1086,C001,Alice Williams,Mechanical Pencil,Office Supplies,Writing,6,6.99,41.94,0,...,2023-04-13,Standard,East,New York,New York,Consumer,PayPal,8.38,Store,False
88,1089,C078,Amy Flores,Index Cards,Office Supplies,Paper,10,3.99,39.90,0,...,2023-04-16,Standard,South,Oklahoma,Tulsa,Home Office,PayPal,7.98,Store,False
116,1117,C104,Andy Bass,Paper Cutter,Office Supplies,Tools,1,39.99,39.99,5,...,2023-05-14,Standard,West,Arizona,Mesa,Corporate,Debit Card,7.99,Online,False
144,1145,C130,Adam Knox,Wrist Rest,Office Supplies,Accessories,3,12.99,38.97,0,...,2023-06-11,Standard,West,Washington,Bellevue,Home Office,PayPal,7.79,Online,False
173,1174,C156,Alma Haas,Mini Fridge,Electronics,Home,1,199.99,199.99,12,...,2023-07-10,Express,South,Texas,Laredo,Consumer,Debit Card,39.99,Online,False

In [ ]:
#PRODUCTS ENDING WITH DESK
df.loc[df.product_name.str.endswith('Desk')]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
38,1039,C033,Hannah Perez,Corner Desk,Furniture,Desks,1,349.99,349.99,12,...,2023-02-26,Standard,Central,Kansas,Wichita,Home Office,PayPal,69.99,Online,False
72,1073,C063,Lisa Kelly,L-Shaped Desk,Furniture,Desks,1,499.99,499.99,15,...,2023-04-01,Standard,West,California,San Diego,Consumer,Credit Card,99.99,Store,False
101,1102,C090,Mona Myers,Reception Desk,Furniture,Desks,1,699.99,699.99,20,...,2023-05-01,Standard,West,Washington,Tacoma,Corporate,PayPal,139.99,Store,False

In [ ]:
#orders from cities containing new
df.loc[df.city.str.contains("New")]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
11,1012,C001,Alice Williams,Paper Clips,Office Supplies,Organizers,10,2.99,29.90,0,...,2023-01-29,Standard,East,New York,New York,Consumer,Credit Card,8.97,Store,False
15,1016,C014,Noah Rodriguez,Webcam HD,Electronics,Accessories,1,79.99,79.99,5,...,2023-02-02,Express,East,New Jersey,Newark,Consumer,Credit Card,15.99,Online,False
27,1028,C024,Xavier Allen,Folders,Office Supplies,Organizers,12,3.99,47.88,0,...,2023-02-14,Standard,South,Louisiana,New Orleans,Home Office,PayPal,9.57,Store,False
30,1031,C001,Alice Williams,External SSD,Electronics,Storage,1,149.99,149.99,8,...,2023-02-16,Express,East,New York,New York,Consumer,Credit Card,29.99,Online,False
85,1086,C001,Alice Williams,Mechanical Pencil,Office Supplies,Writing,6,6.99,41.94,0,...,2023-04-13,Standard,East,New York,New York,Consumer,PayPal,8.38,Store,False
98,1099,C088,Kara Diaz,Standing Mat,Office Supplies,Accessories,1,44.99,44.99,8,...,2023-04-26,Standard,East,Connecticut,New Haven,Home Office,Credit Card,8.99,Store,False
139,1140,C125,Vera Pena,Smart Lock,Electronics,Security,1,179.99,179.99,15,...,2023-06-06,Express,East,Virginia,Newport News,Consumer,Credit Card,35.99,Online,False
170,1171,C153,Xara Kemp,Alarm Clock,Electronics,Home,2,29.99,59.98,5,...,2023-07-07,Standard,East,New York,New Rochelle,Consumer,Debit Card,11.99,Online,False

In [ ]:
df.loc[df.category.isin(['Electronics', 'Office Supplies'])]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
7,1008,C007,Grace Lee,Printer Ink,Office Supplies,Printing,4,29.99,119.96,5,...,2023-01-25,Standard,Central,Ohio,Columbus,Consumer,Credit Card,23.99,Store,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,2023-07-31,Standard,West,Washington,Renton,Home Office,Debit Card,8.37,Store,False
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False

In [ ]:
#specific states
df.loc[df.state.isin(['New York','California'])]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
11,1012,C001,Alice Williams,Paper Clips,Office Supplies,Organizers,10,2.99,29.90,0,...,2023-01-29,Standard,East,New York,New York,Consumer,Credit Card,8.97,Store,False
30,1031,C001,Alice Williams,External SSD,Electronics,Storage,1,149.99,149.99,8,...,2023-02-16,Express,East,New York,New York,Consumer,Credit Card,29.99,Online,False
42,1043,C002,Bob Johnson,Mouse Pad,Electronics,Accessories,4,12.99,51.96,5,...,2023-03-01,Standard,West,California,Los Angeles,Corporate,Credit Card,10.39,Online,False
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
62,1063,C054,Carl Howard,Docking Station,Electronics,Accessories,1,159.99,159.99,12,...,2023-03-21,Express,East,New York,Buffalo,Corporate,Debit Card,31.99,Online,False
72,1073,C063,Lisa Kelly,L-Shaped Desk,Furniture,Desks,1,499.99,499.99,15,...,2023-04-01,Standard,West,California,San Diego,Consumer,Credit Card,99.99,Store,False
85,1086,C001,Alice Williams,Mechanical Pencil,Office Supplies,Writing,6,6.99,41.94,0,...,2023-04-13,Standard,East,New York,New York,Consumer,PayPal,8.38,Store,False
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True
105,1106,C094,Queen Vargas,Desk Pad Leather,Office Supplies,Accessories,2,29.99,59.98,5,...,2023-05-03,Standard,West,California,Fresno,Home Office,PayPal,11.99,Online,False
112,1113,C002,Bob Johnson,Coffee Table,Furniture,Tables,1,199.99,199.99,10,...,2023-05-11,Standard,West,California,Los Angeles,Corporate,Credit Card,39.99,Store,False
124,1125,C111,Holly Walsh,Lounge Chair,Furniture,Seating,1,249.99,249.99,15,...,2023-05-23,Standard,West,California,Sacramento,Consumer,Credit Card,49.99,Store,False
125,1126,C112,Igor Norman,Rubber Stamp,Office Supplies,Tools,2,12.99,25.98,0,...,2023-05-23,Standard,East,New York,Yonkers,Home Office,Debit Card,5.19,Store,False
143,1144,C129,Zoe Hines,Bar Cart,Furniture,Storage,1,159.99,159.99,12,...,2023-06-11,Standard,East,New York,Syracuse,Consumer,Debit Card,31.99,Store,False
145,1146,C002,Bob Johnson,Printer Wireless,Electronics,Printing,1,179.99,179.99,10,...,2023-06-12,Express,West,California,Los Angeles,Corporate,Credit Card,35.99,Online,False
154,1155,C138,Iris Cochran,Erasers,Office Supplies,Writing,12,1.99,23.88,0,...,2023-06-21,Standard,West,California,Anaheim,Consumer,Credit Card,4.77,Store,False
161,1162,C145,Pete Weeks,Backup Battery,Electronics,Accessories,1,89.99,89.99,12,...,2023-06-28,Express,East,New York,Albany,Consumer,Debit Card,17.99,Online,False
170,1171,C153,Xara Kemp,Alarm Clock,Electronics,Home,2,29.99,59.98,5,...,2023-07-07,Standard,East,New York,New Rochelle,Consumer,Debit Card,11.99,Online,False
171,1172,C154,Yuri Knapp,Dresser,Furniture,Storage,1,299.99,299.99,15,...,2023-07-09,Standard,West,California,Santa Clarita,Consumer,PayPal,59.99,Store,False
181,1182,C002,Bob Johnson,Memory Card,Electronics,Storage,3,24.99,74.97,8,...,2023-07-18,Standard,West,California,Los Angeles,Corporate,Credit Card,14.99,Online,False
190,1191,C171,Paul Ware,Shelving Unit,Furniture,Storage,1,129.99,129.99,10,...,2023-07-28,Standard,West,California,Irvine,Consumer,Credit Card,25.99,Store,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False

In [ ]:
#specific payment methods
df.loc[df.payment_method.isin(['Debit Card','Credit Card'])]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
5,1006,C005,Emma Davis,Monitor 27inch,Electronics,Computers,1,299.99,299.99,20,...,2023-01-23,Express,East,Massachusetts,Boston,Consumer,Credit Card,59.99,Online,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1194,C174,Sage Berg,Patio Chair,Furniture,Outdoor,2,69.99,139.98,15,...,2023-07-31,Standard,Central,Indiana,Carmel,Consumer,Credit Card,27.99,Store,False
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,2023-07-31,Standard,West,Washington,Renton,Home Office,Debit Card,8.37,Store,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

**not condition**

In [ ]:
#non consumer segment
df.loc[~df.customer_segment.isin(['Consumer'])]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
6,1007,C006,Frank Miller,Desk Lamp,Furniture,Lighting,2,39.99,79.98,10,...,2023-01-24,Standard,West,Washington,Seattle,Home Office,PayPal,15.99,Online,False
9,1010,C009,Isabel Martinez,Bookshelf,Furniture,Storage,1,189.99,189.99,8,...,2023-01-28,Standard,East,Pennsylvania,Philadelphia,Home Office,Debit Card,37.99,Store,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,1188,C169,Nash Todd,Coat Hooks,Furniture,Accessories,3,14.99,44.97,8,...,2023-07-24,Standard,East,New Jersey,Trenton,Home Office,Credit Card,8.99,Store,False
191,1192,C172,Quin Rosa,Desk Accessories Set,Office Supplies,Organizers,2,24.99,49.98,5,...,2023-07-28,Standard,South,North Carolina,Fayetteville,Home Office,Debit Card,9.99,Store,False
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,2023-07-31,Standard,West,Washington,Renton,Home Office,Debit Card,8.37,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

In [ ]:
#oders with discount
df.loc[df['discount_percent']==0]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
11,1012,C001,Alice Williams,Paper Clips,Office Supplies,Organizers,10,2.99,29.90,0,...,2023-01-29,Standard,East,New York,New York,Consumer,Credit Card,8.97,Store,False
14,1015,C013,Mia Garcia,Stapler,Office Supplies,Organizers,3,8.99,26.97,0,...,2023-01-31,Standard,West,Nevada,Las Vegas,Home Office,PayPal,5.39,Store,False
17,1018,C003,Carol Smith,USB Flash Drive,Electronics,Accessories,5,15.99,79.95,0,...,2023-02-03,Standard,Central,Illinois,Chicago,Home Office,PayPal,15.99,Online,False
20,1021,C018,Rachel Clark,Pen Set,Office Supplies,Writing,8,5.99,47.92,0,...,2023-02-07,Standard,East,Virginia,Richmond,Home Office,PayPal,9.58,Store,False
25,1026,C022,Victor Young,Monitor Stand,Furniture,Accessories,2,34.99,69.98,0,...,2023-02-12,Standard,Central,Indiana,Indianapolis,Consumer,Credit Card,13.99,Online,False
27,1028,C024,Xavier Allen,Folders,Office Supplies,Organizers,12,3.99,47.88,0,...,2023-02-14,Standard,South,Louisiana,New Orleans,Home Office,PayPal,9.57,Store,False
31,1032,C027,Betty Scott,Markers,Office Supplies,Writing,6,7.99,47.94,0,...,2023-02-18,Standard,South,Oklahoma,Oklahoma City,Home Office,PayPal,9.58,Store,False
34,1035,C030,Eric Baker,Calculator,Office Supplies,Tools,3,24.99,74.97,0,...,2023-02-21,Standard,Central,Iowa,Des Moines,Home Office,PayPal,14.99,Store,False
36,1037,C031,Fiona Carter,Desk Mat,Office Supplies,Accessories,2,15.99,31.98,0,...,2023-02-23,Standard,West,Idaho,Boise,Consumer,Debit Card,6.39,Online,False
39,1040,C034,Ian Roberts,Cable Organizer,Office Supplies,Organizers,5,9.99,49.95,0,...,2023-02-26,Standard,South,Arkansas,Little Rock,Consumer,Debit Card,9.99,Store,False
41,1042,C036,Kevin Phillips,Highlighters,Office Supplies,Writing,10,4.99,49.90,0,...,2023-02-28,Standard,East,New Hampshire,Manchester,Home Office,PayPal,9.98,Store,False
43,1044,C037,Laura Campbell,Filing Tray,Office Supplies,Organizers,3,14.99,44.97,0,...,2023-03-02,Standard,Central,Nebraska,Omaha,Consumer,Debit Card,8.99,Store,False
47,1048,C013,Mia Garcia,Laptop Stand,Electronics,Accessories,1,44.99,44.99,0,...,2023-03-06,Standard,West,Nevada,Las Vegas,Home Office,PayPal,8.99,Store,False
51,1052,C044,Steve Morris,HDMI Cable,Electronics,Accessories,3,14.99,44.97,0,...,2023-03-09,Standard,West,Alaska,Anchorage,Consumer,Credit Card,8.99,Online,False
54,1055,C047,Vera Cook,Desk Calendar,Office Supplies,Planning,4,9.99,39.96,0,...,2023-03-13,Standard,South,Kentucky,Louisville,Consumer,Credit Card,7.99,Store,False
57,1058,C050,Yusuf Rivera,Surge Protector,Electronics,Accessories,4,19.99,79.96,0,...,2023-03-16,Standard,East,South Carolina,Columbia,Home Office,PayPal,15.99,Online,False
59,1060,C051,Zoe Cooper,Clipboard,Office Supplies,Organizers,6,6.99,41.94,0,...,2023-03-18,Standard,South,Virginia,Norfolk,Home Office,Debit Card,8.38,Store,False
61,1062,C053,Bella Cox,Sticky Notes,Office Supplies,Paper,15,3.99,59.85,0,...,2023-03-20,Standard,Central,Illinois,Springfield,Consumer,Credit Card,11.97,Store,False
64,1065,C056,Ethan Torres,Tape Dispenser,Office Supplies,Organizers,5,7.99,39.95,0,...,2023-03-23,Standard,West,Oregon,Salem,Consumer,Credit Card,7.99,Store,False
68,1069,C060,Ivan James,Cooling Pad,Electronics,Accessories,1,24.99,24.99,0,...,2023-03-27,Standard,West,Washington,Spokane,Consumer,Debit Card,4.99,Online,False
70,1071,C061,Jane Watson,Paper Tray,Office Supplies,Organizers,3,12.99,38.97,0,...,2023-03-29,Standard,Central,Michigan,Grand Rapids,Home Office,Credit Card,7.79,Store,False
73,1074,C064,Mark Sanders,Envelopes,Office Supplies,Paper,20,2.99,59.80,0,...,2023-04-01,Standard,South,North Carolina,Raleigh,Home Office,PayPal,11.96,Store,False
78,1079,C069,Rose Ross,Desk Drawer,Furniture,Storage,2,39.99,79.98,0,...,2023-04-06,Standard,Central,Indiana,Fort Wayne,Home Office,Debit Card,15.99,Store,False
79,1080,C070,Sean Henderson,Correction Tape,Office Supplies,Writing,8,4.99,39.92,0,...,2023-04-07,Standard,East,Virginia,Virginia Beach,Consumer,PayPal,7.98,Store,False
84,1085,C075,Xyla Long,Hole Punch,Office Supplies,Tools,4,9.99,39.96,0,...,2023-04-12,Standard,South,Louisiana,Baton Rouge,Home Office,Debit Card,7.99,Store,False
85,1086,C001,Alice Williams,Mechanical Pencil,Office Supplies,Writing,6,6.99,41.94,0,...,2023-04-13,Standard,East,New York,New York,Consumer,PayPal,8.38,Store,False
88,1089,C078,Amy Flores,Index Cards,Office Supplies,Paper,10,3.99,39.90,0,...,2023-04-16,Standard,South,Oklahoma,Tulsa,Home Office,PayPal,7.98,Store,False
91,1092,C081,Dean Simmons,Planner,Office Supplies,Planning,3,14.99,44.97,0,...,2023-04-19,Standard,Central,Iowa,Cedar Rapids,Consumer,PayPal,8.99,Store,False
96,1097,C086,Iris Russell,Binder Clips,Office Supplies,Organizers,12,2.99,35.88,0,...,2023-04-24,Standard,South,Arkansas,Fort Smith,Home Office,Debit Card,7.17,Store,False
102,1103,C091,Nate Ford,Rubber Bands,Office Supplies,Organizers,15,1.99,29.85,0,...,2023-04-30,Standard,Central,Kansas,Overland Park,Home Office,Debit Card,5.97,Store,False
107,1108,C096,Sara Duncan,Pen Holder,Office Supplies,Organizers,5,8.99,44.95,0,...,2023-05-05,Standard,East,Maryland,Rockville,Consumer,Debit Card,8.99,Store,False
110,1111,C099,Vance Boyd,Letter Opener,Office Supplies,Tools,3,5.99,17.97,0,...,2023-05-08,Standard,Central,Michigan,Ann Arbor,Consumer,Debit Card,3.59,Store,False
113,1114,C101,Xander Aguilar,Scissors,Office Supplies,Tools,7,4.99,34.93,0,...,2023-05-11,Standard,South,Florida,Jacksonville,Home Office,Debit Card,6.98,Store,False
119,1120,C107,Dana Mann,Tape,Office Supplies,Accessories,10,2.99,29.90,0,...,2023-05-17,Standard,East,Massachusetts,Lowell,Home Office,Debit Card,5.98,Store,False
122,1123,C110,Greg Watts,Name Tags,Office Supplies,Organizers,8,3.99,31.92,0,...,2023-05-20,Standard,Central,Ohio,Akron,Corporate,Debit Card,6.38,Store,False
125,1126,C112,Igor Norman,Rubber Stamp,Office Supplies,Tools,2,12.99,25.98,0,...,2023-05-23,Standard,East,New York,Yonkers,Home Office,Debit Card,5.19,Store,False
128,1129,C115,Lena Walsh,Dry Erase Markers,Office Supplies,Writing,9,5.99,53.91,0,...,2023-05-26,Standard,West,Oregon,Gresham,Consumer,Debit Card,10.78,Store,False
131,1132,C118,Otto Frank,Push Pins,Office Supplies,Organizers,11,2.99,32.89,0,...,2023-05-29,Standard,South,North Carolina,Greensboro,Consumer,Debit Card,6.57,Store,False
138,1139,C124,Ulysses Horn,Glue Sticks,Office Supplies,Accessories,14,2.99,41.86,0,...,2023-06-05,Standard,Central,Wisconsin,Kenosha,Home Office,PayPal,8.37,Store,False
141,1142,C127,Xena Lowe,Staples,Office Supplies,Organizers,16,1.99,31.84,0,...,2023-06-08,Standard,West,Arizona,Chandler,Home Office,PayPal,6.36,Store,False
144,1145,C130,Adam Knox,Wrist Rest,Office Supplies,Accessories,3,12.99,38.97,0,...,2023-06-11,Standard,West,Washington,Bellevue,Home Office,PayPal,7.79,Online,False
147,1148,C132,Clare Howe,Laminating Sheets,Office Supplies,Accessories,6,6.99,41.94,0,...,2023-06-14,Standard,Central,Ohio,Dayton,Home Office,PayPal,8.38,Store,False
150,1151,C135,Ford Blake,Dividers,Office Supplies,Organizers,9,4.99,44.91,0,...,2023-06-17,Standard,South,Louisiana,Metairie,Home Office,PayPal,8.98,Store,False
154,1155,C138,Iris Cochran,Erasers,Office Supplies,Writing,12,1.99,23.88,0,...,2023-06-21,Standard,West,California,Anaheim,Consumer,Credit Card,4.77,Store,False
157,1158,C141,Lance Rodgers,Binder,Office Supplies,Organizers,7,8.99,62.93,0,...,2023-06-24,Standard,East,Massachusetts,Cambridge,Home Office,Credit Card,12.58,Store,False
160,1161,C144,Orla Prince,Tacks,Office Supplies,Organizers,13,2.99,38.87,0,...,2023-06-27,Standard,South,North Carolina,Winston-Salem,Home Office,Credit Card,7.77,Store,False
163,1164,C147,Remy Kirk,Pencil Sharpener,Office Supplies,Tools,4,7.99,31.96,0,...,2023-06-30,Standard,Central,Indiana,South Bend,Consumer,Credit Card,6.39,Store,False
166,1167,C150,Unity Pace,Pencil Case,Office Supplies,Organizers,5,5.99,29.95,0,...,2023-07-03,Standard,West,Oregon,Hillsboro,Home Office,Credit Card,5.99,Store,False
169,1170,C152,Wade Dotson,Ink Pads,Office Supplies,Accessories,4,6.99,27.96,0,...,2023-07-06,Standard,South,Tennessee,Clarksville,Consumer,Credit Card,5.59,Store,False
172,1173,C155,Zain Weiss,Graph Paper,Office Supplies,Paper,8,3.99,31.92,0,...,2023-07-09,Standard,Central,Illinois,Elgin,Home Office,Credit Card,6.38,Store,False
175,1176,C158,Cleo Mann,Correction Fluid,Office Supplies,Writing,10,3.99,39.90,0,...,2023-07-12,Standard,West,Washington,Everett,Home Office,Credit Card,7.98,Store,False
176,1177,C159,Dax Boone,Tablet Holder,Electronics,Accessories,1,19.99,19.99,0,...,2023-07-13,Standard,Central,Minnesota,Brooklyn Park,Consumer,Debit Card,3.99,Online,False
178,1179,C161,Finn Huff,Color Pencils,Office Supplies,Writing,6,8.99,53.94,0,...,2023-07-15,Standard,East,Massachusetts,Brockton,Home Office,PayPal,10.78,Store,False
185,1186,C167,Lila Moon,Report Covers,Office Supplies,Presentation,8,4.99,39.92,0,...,2023-07-22,Standard,West,Oregon,Beaverton,Home Office,Debit Card,7.98,Store,False
188,1189,C170,Oona Clay,Crayons,Office Supplies,Writing,11,3.99,43.89,0,...,2023-07-25,Standard,Central,Michigan,Livonia,Consumer,Debit Card,8.77,Store,False
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,2023-07-31,Standard,West,Washington,Renton,Home Office,Debit Card,8.37,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False

In [ ]:
#non-returned items
df.loc[df['returned']==False]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
2,1003,C003,Carol Smith,Wireless Mouse,Electronics,Accessories,3,25.99,77.97,0,...,2023-01-19,Express,Central,Illinois,Chicago,Home Office,PayPal,15.59,Online,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

In [ ]:
#not from electronics category
df.loc[df['category']!='Electronics']

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
3,1004,C004,David Brown,Standing Desk,Furniture,Desks,1,449.99,449.99,15,...,2023-01-22,Standard,South,Texas,Houston,Consumer,Credit Card,89.99,Online,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
6,1007,C006,Frank Miller,Desk Lamp,Furniture,Lighting,2,39.99,79.98,10,...,2023-01-24,Standard,West,Washington,Seattle,Home Office,PayPal,15.99,Online,False
7,1008,C007,Grace Lee,Printer Ink,Office Supplies,Printing,4,29.99,119.96,5,...,2023-01-25,Standard,Central,Ohio,Columbus,Consumer,Credit Card,23.99,Store,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1194,C174,Sage Berg,Patio Chair,Furniture,Outdoor,2,69.99,139.98,15,...,2023-07-31,Standard,Central,Indiana,Carmel,Consumer,Credit Card,27.99,Store,False
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,2023-07-31,Standard,West,Washington,Renton,Home Office,Debit Card,8.37,Store,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

In [ ]:
#specific states
df.loc[df.state.isin(['New York','California'])]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
0,1001,C001,Alice Williams,Laptop,Electronics,Computers,1,899.99,899.99,10,...,2023-01-18,Express,East,New York,New York,Consumer,Credit Card,179.99,Online,False
1,1002,C002,Bob Johnson,Office Chair,Furniture,Chairs,2,149.99,299.98,5,...,2023-01-20,Standard,West,California,Los Angeles,Corporate,Debit Card,44.99,Store,False
4,1005,C002,Bob Johnson,Notebook Set,Office Supplies,Paper,5,12.99,64.95,0,...,2023-01-21,Standard,West,California,Los Angeles,Corporate,Debit Card,19.48,Store,False
11,1012,C001,Alice Williams,Paper Clips,Office Supplies,Organizers,10,2.99,29.90,0,...,2023-01-29,Standard,East,New York,New York,Consumer,Credit Card,8.97,Store,False
30,1031,C001,Alice Williams,External SSD,Electronics,Storage,1,149.99,149.99,8,...,2023-02-16,Express,East,New York,New York,Consumer,Credit Card,29.99,Online,False
42,1043,C002,Bob Johnson,Mouse Pad,Electronics,Accessories,4,12.99,51.96,5,...,2023-03-01,Standard,West,California,Los Angeles,Corporate,Credit Card,10.39,Online,False
60,1061,C052,Aaron Richardson,Monitor 32inch,Electronics,Computers,1,449.99,449.99,18,...,2023-03-19,Express,West,California,San Francisco,Consumer,PayPal,89.99,Online,False
62,1063,C054,Carl Howard,Docking Station,Electronics,Accessories,1,159.99,159.99,12,...,2023-03-21,Express,East,New York,Buffalo,Corporate,Debit Card,31.99,Online,False
72,1073,C063,Lisa Kelly,L-Shaped Desk,Furniture,Desks,1,499.99,499.99,15,...,2023-04-01,Standard,West,California,San Diego,Consumer,Credit Card,99.99,Store,False
85,1086,C001,Alice Williams,Mechanical Pencil,Office Supplies,Writing,6,6.99,41.94,0,...,2023-04-13,Standard,East,New York,New York,Consumer,PayPal,8.38,Store,False
94,1095,C084,Gina Bryant,VR Headset,Electronics,Gaming,1,399.99,399.99,20,...,2023-04-23,Express,East,New York,Rochester,Consumer,PayPal,79.99,Online,True
105,1106,C094,Queen Vargas,Desk Pad Leather,Office Supplies,Accessories,2,29.99,59.98,5,...,2023-05-03,Standard,West,California,Fresno,Home Office,PayPal,11.99,Online,False
112,1113,C002,Bob Johnson,Coffee Table,Furniture,Tables,1,199.99,199.99,10,...,2023-05-11,Standard,West,California,Los Angeles,Corporate,Credit Card,39.99,Store,False
124,1125,C111,Holly Walsh,Lounge Chair,Furniture,Seating,1,249.99,249.99,15,...,2023-05-23,Standard,West,California,Sacramento,Consumer,Credit Card,49.99,Store,False
125,1126,C112,Igor Norman,Rubber Stamp,Office Supplies,Tools,2,12.99,25.98,0,...,2023-05-23,Standard,East,New York,Yonkers,Home Office,Debit Card,5.19,Store,False
143,1144,C129,Zoe Hines,Bar Cart,Furniture,Storage,1,159.99,159.99,12,...,2023-06-11,Standard,East,New York,Syracuse,Consumer,Debit Card,31.99,Store,False
145,1146,C002,Bob Johnson,Printer Wireless,Electronics,Printing,1,179.99,179.99,10,...,2023-06-12,Express,West,California,Los Angeles,Corporate,Credit Card,35.99,Online,False
154,1155,C138,Iris Cochran,Erasers,Office Supplies,Writing,12,1.99,23.88,0,...,2023-06-21,Standard,West,California,Anaheim,Consumer,Credit Card,4.77,Store,False
161,1162,C145,Pete Weeks,Backup Battery,Electronics,Accessories,1,89.99,89.99,12,...,2023-06-28,Express,East,New York,Albany,Consumer,Debit Card,17.99,Online,False
170,1171,C153,Xara Kemp,Alarm Clock,Electronics,Home,2,29.99,59.98,5,...,2023-07-07,Standard,East,New York,New Rochelle,Consumer,Debit Card,11.99,Online,False
171,1172,C154,Yuri Knapp,Dresser,Furniture,Storage,1,299.99,299.99,15,...,2023-07-09,Standard,West,California,Santa Clarita,Consumer,PayPal,59.99,Store,False
181,1182,C002,Bob Johnson,Memory Card,Electronics,Storage,3,24.99,74.97,8,...,2023-07-18,Standard,West,California,Los Angeles,Corporate,Credit Card,14.99,Online,False
190,1191,C171,Paul Ware,Shelving Unit,Furniture,Storage,1,129.99,129.99,10,...,2023-07-28,Standard,West,California,Irvine,Consumer,Credit Card,25.99,Store,False
192,1193,C173,Rory Pace,Digital Pen,Electronics,Accessories,1,99.99,99.99,12,...,2023-07-29,Express,East,New York,Mount Vernon,Consumer,PayPal,19.99,Online,False

**date filtering**

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [8]:
#orders in jan 2023
res = df[(df['order_date'] >= '2023-01-01') & (df['order_date'] < '2023-02-01')]
print(res)

    order_id customer_id    customer_name         product_name  \
0       1001        C001   Alice Williams               Laptop
1       1002        C002      Bob Johnson         Office Chair
2       1003        C003      Carol Smith       Wireless Mouse
3       1004        C004      David Brown        Standing Desk
4       1005        C002      Bob Johnson         Notebook Set
5       1006        C005       Emma Davis       Monitor 27inch
6       1007        C006     Frank Miller            Desk Lamp
7       1008        C007        Grace Lee          Printer Ink
8       1009        C008     Henry Taylor           Smartphone
9       1010        C009  Isabel Martinez            Bookshelf
10      1011        C010    Jack Anderson  Keyboard Mechanical
11      1012        C001   Alice Williams          Paper Clips
12      1013        C011      Kate Wilson        Tablet 10inch
13      1014        C012    Liam Thompson      Executive Chair
14      1015        C013       Mia Garcia              Stapler
15      1016        C014   Noah Rodriguez            Webcam HD
16      1017        C015  Olivia Martinez         File Cabinet

           category sub_category  quantity  unit_price  total_amount  \
0       Electronics    Computers         1      899.99        899.99
1         Furniture       Chairs         2      149.99        299.98
2       Electronics  Accessories         3       25.99         77.97
3         Furniture        Desks         1      449.99        449.99
4   Office Supplies        Paper         5       12.99         64.95
5       Electronics    Computers         1      299.99        299.99
6         Furniture     Lighting         2       39.99         79.98
7   Office Supplies     Printing         4       29.99        119.96
8       Electronics       Mobile         1      699.99        699.99
9         Furniture      Storage         1      189.99        189.99
10      Electronics  Accessories         2       89.99        179.98
11  Office Supplies   Organizers        10        2.99         29.90
12      Electronics       Mobile         1      399.99        399.99
13        Furniture       Chairs         1      299.99        299.99
14  Office Supplies   Organizers         3        8.99         26.97
15      Electronics  Accessories         1       79.99         79.99
16        Furniture      Storage         1      159.99        159.99

    discount_percent  ...   ship_date ship_mode   region          state  \
0                 10  ...  2023-01-18   Express     East       New York
1                  5  ...  2023-01-20  Standard     West     California
2                  0  ...  2023-01-19   Express  Central       Illinois
3                 15  ...  2023-01-22  Standard    South          Texas
4                  0  ...  2023-01-21  Standard     West     California
5                 20  ...  2023-01-23   Express     East  Massachusetts
6                 10  ...  2023-01-24  Standard     West     Washington
7                  5  ...  2023-01-25  Standard  Central           Ohio
8                 12  ...  2023-01-26   Express    South        Florida
9                  8  ...  2023-01-28  Standard     East   Pennsylvania
10                10  ...  2023-01-27   Express     West         Oregon
11                 0  ...  2023-01-29  Standard     East       New York
12                15  ...  2023-01-30   Express  Central       Michigan
13                10  ...  2023-02-01  Standard    South        Georgia
14                 0  ...  2023-01-31  Standard     West         Nevada
15                 5  ...  2023-02-02   Express     East     New Jersey
16                12  ...  2023-02-03  Standard  Central      Minnesota

            city customer_segment payment_method  profit  sales_channel  \
0       New York         Consumer    Credit Card  179.99         Online
1    Los Angeles        Corporate     Debit Card   44.99          Store
2        Chicago      Home Office         PayPal   15.59         Online
3        Houston         Consumer    Credit Card   89.99         Online
4    Los Angeles        Corporate     Debit Card   19.48          Store
5         Boston         Consumer    Credit Card   59.99         Online
6        Seattle      Home Office         PayPal   15.99         Online
7       Columbus         Consumer    Credit Card   23.99          Store
8          Miami         Consumer    Credit Card  139.99         Online
9   Philadelphia      Home Office     Debit Card   37.99          Store
10      Portland         Consumer         PayPal   35.99         Online
11      New York         Consumer    Credit Card    8.97          Store
12       Detroit        Corporate    Credit Card   79.99         Online
13       Atlanta        Corporate     Debit Card   59.99          Store
14     Las Vegas      Home Office         PayPal    5.39          Store
15        Newark         Consumer    Credit Card   15.99         Online
16   Minneapolis        Corporate     Debit Card   31.99          Store

   returned
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False

[17 rows x 21 columns]

In [7]:
#orders after 2023 march
df.loc[df['order_date'] > '2023-03-01']

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_date,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned
46,1047,C040,Oscar Edwards,Label Maker,Office Supplies,Tools,1,49.99,49.99,8,...,2023-03-05,Standard,West,Wyoming,Cheyenne,Corporate,Debit Card,9.99,Online,False
47,1048,C013,Mia Garcia,Laptop Stand,Electronics,Accessories,1,44.99,44.99,0,...,2023-03-06,Standard,West,Nevada,Las Vegas,Home Office,PayPal,8.99,Store,False
48,1049,C041,Paula Collins,Bulletin Board,Office Supplies,Presentation,2,29.99,59.98,10,...,2023-03-07,Standard,Central,South Dakota,Sioux Falls,Consumer,Credit Card,11.99,Store,False
49,1050,C042,Quincy Stewart,Graphics Card,Electronics,Computers,1,399.99,399.99,15,...,2023-03-08,Express,East,Rhode Island,Providence,Consumer,Debit Card,79.99,Online,False
50,1051,C043,Rita Sanchez,Paper Shredder,Office Supplies,Tools,1,129.99,129.99,12,...,2023-03-10,Standard,South,Alabama,Birmingham,Corporate,PayPal,25.99,Store,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,C176,Umar Shaw,Car Vacuum,Electronics,Auto,1,59.99,59.99,10,...,2023-08-01,Standard,South,Georgia,Macon,Consumer,PayPal,11.99,Online,False
196,1197,C177,Vale Horn,Garden Bench,Furniture,Outdoor,1,149.99,149.99,12,...,2023-08-03,Standard,East,Virginia,Hampton,Consumer,Credit Card,29.99,Store,False
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,2023-08-03,Standard,Central,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False
198,1199,C179,Xena Pace,Battery Pack,Electronics,Accessories,2,44.99,89.98,8,...,2023-08-04,Standard,West,Nevada,Carson City,Consumer,PayPal,17.99,Online,False
199,1200,C180,Yara Love,Umbrella Stand,Furniture,Accessories,1,29.99,29.99,5,...,2023-08-05,Standard,South,Tennessee,Murfreesboro,Home Office,Credit Card,5.99,Store,False

In [9]:
#calculate shipping duration > 5 days
df['ship_date'] = pd.to_datetime(df['ship_date'])
df['order_date'] = pd.to_datetime(df['order_date'])
df['shipping_duration'] = (df['ship_date'] - df['order_date']).dt.days
df.loc[df['shipping_duration'] > 5]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, product_name, category, sub_category, quantity, unit_price, total_amount, discount_percent, order_date, ship_date, ship_mode, region, state, city, customer_segment, payment_method, profit, sales_channel, returned, shipping_duration]
Index: []

[0 rows x 22 columns]

**sorting and top/bottom values**

In [10]:
#top 10 highest values orders
res = df.nlargest(10, 'total_amount')
print(res)

     order_id customer_id     customer_name      product_name     category  \
0        1001        C001    Alice Williams            Laptop  Electronics
22       1023        C020       Tina Walker  Conference Table    Furniture
8        1009        C008      Henry Taylor        Smartphone  Electronics
101      1102        C090        Mona Myers    Reception Desk    Furniture
29       1030        C026       Zack Wright              Sofa    Furniture
103      1104        C092        Opal Wells      Drone Camera  Electronics
40       1041        C035      Julia Turner         Projector  Electronics
72       1073        C063        Lisa Kelly     L-Shaped Desk    Furniture
3        1004        C004       David Brown     Standing Desk    Furniture
60       1061        C052  Aaron Richardson    Monitor 32inch  Electronics

     sub_category  quantity  unit_price  total_amount  discount_percent  ...  \
0       Computers         1      899.99        899.99                10  ...
22         Tables         1      799.99        799.99                20  ...
8          Mobile         1      699.99        699.99                12  ...
101         Desks         1      699.99        699.99                20  ...
29        Seating         1      599.99        599.99                15  ...
103   Photography         1      599.99        599.99                18  ...
40   Presentation         1      499.99        499.99                20  ...
72          Desks         1      499.99        499.99                15  ...
3           Desks         1      449.99        449.99                15  ...
60      Computers         1      449.99        449.99                18  ...

    ship_mode   region       state           city customer_segment  \
0     Express     East    New York       New York         Consumer
22   Standard    South   Tennessee      Nashville        Corporate
8     Express    South     Florida          Miami         Consumer
101  Standard     West  Washington         Tacoma        Corporate
29   Standard  Central    Missouri    Kansas City         Consumer
103   Express     East    Virginia     Chesapeake         Consumer
40    Express     West     Montana       Billings        Corporate
72   Standard     West  California      San Diego         Consumer
3    Standard    South       Texas        Houston         Consumer
60    Express     West  California  San Francisco         Consumer

    payment_method  profit sales_channel  returned shipping_duration
0      Credit Card  179.99        Online     False                 3
22     Credit Card  159.99         Store     False                 4
8      Credit Card  139.99        Online     False                 3
101         PayPal  139.99         Store     False                 5
29      Debit Card  119.99         Store     False                 4
103    Credit Card  119.99        Online     False                 4
40     Credit Card   99.99        Online      True                 4
72     Credit Card   99.99         Store     False                 4
3      Credit Card   89.99        Online     False                 4
60          PayPal   89.99        Online     False                 3

[10 rows x 22 columns]

In [ ]:
#bottom 10 lowest value orders
df.nsmallest(10, 'total_amount')

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned,shipping_duration
110,1111,C099,Vance Boyd,Letter Opener,Office Supplies,Tools,3,5.99,17.97,0,...,Standard,Central,Michigan,Ann Arbor,Consumer,Debit Card,3.59,Store,False,3 days
176,1177,C159,Dax Boone,Tablet Holder,Electronics,Accessories,1,19.99,19.99,0,...,Standard,Central,Minnesota,Brooklyn Park,Consumer,Debit Card,3.99,Online,False,3 days
154,1155,C138,Iris Cochran,Erasers,Office Supplies,Writing,12,1.99,23.88,0,...,Standard,West,California,Anaheim,Consumer,Credit Card,4.77,Store,False,3 days
68,1069,C060,Ivan James,Cooling Pad,Electronics,Accessories,1,24.99,24.99,0,...,Standard,West,Washington,Spokane,Consumer,Debit Card,4.99,Online,False,3 days
125,1126,C112,Igor Norman,Rubber Stamp,Office Supplies,Tools,2,12.99,25.98,0,...,Standard,East,New York,Yonkers,Home Office,Debit Card,5.19,Store,False,3 days
14,1015,C013,Mia Garcia,Stapler,Office Supplies,Organizers,3,8.99,26.97,0,...,Standard,West,Nevada,Las Vegas,Home Office,PayPal,5.39,Store,False,2 days
169,1170,C152,Wade Dotson,Ink Pads,Office Supplies,Accessories,4,6.99,27.96,0,...,Standard,South,Tennessee,Clarksville,Consumer,Credit Card,5.59,Store,False,3 days
182,1183,C164,Ivan Cash,Magazine Holder,Office Supplies,Organizers,2,13.99,27.98,5,...,Standard,South,Louisiana,Lafayette,Home Office,Debit Card,5.59,Store,False,3 days
102,1103,C091,Nate Ford,Rubber Bands,Office Supplies,Organizers,15,1.99,29.85,0,...,Standard,Central,Kansas,Overland Park,Home Office,Debit Card,5.97,Store,False,3 days
11,1012,C001,Alice Williams,Paper Clips,Office Supplies,Organizers,10,2.99,29.90,0,...,Standard,East,New York,New York,Consumer,Credit Card,8.97,Store,False,3 days

In [11]:
#sort by multiple cols
df.sort_values(['region', 'total_amount'], ascending=[False, True])

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,ship_mode,region,state,city,customer_segment,payment_method,profit,sales_channel,returned,shipping_duration
154,1155,C138,Iris Cochran,Erasers,Office Supplies,Writing,12,1.99,23.88,0,...,Standard,West,California,Anaheim,Consumer,Credit Card,4.77,Store,False,3
68,1069,C060,Ivan James,Cooling Pad,Electronics,Accessories,1,24.99,24.99,0,...,Standard,West,Washington,Spokane,Consumer,Debit Card,4.99,Online,False,3
14,1015,C013,Mia Garcia,Stapler,Office Supplies,Organizers,3,8.99,26.97,0,...,Standard,West,Nevada,Las Vegas,Home Office,PayPal,5.39,Store,False,2
166,1167,C150,Unity Pace,Pencil Case,Office Supplies,Organizers,5,5.99,29.95,0,...,Standard,West,Oregon,Hillsboro,Home Office,Credit Card,5.99,Store,False,3
141,1142,C127,Xena Lowe,Staples,Office Supplies,Organizers,16,1.99,31.84,0,...,Standard,West,Arizona,Chandler,Home Office,PayPal,6.36,Store,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,1039,C033,Hannah Perez,Corner Desk,Furniture,Desks,1,349.99,349.99,12,...,Standard,Central,Kansas,Wichita,Home Office,PayPal,69.99,Online,False,4
87,1088,C077,Zane Hughes,Gaming Chair,Furniture,Chairs,1,349.99,349.99,18,...,Standard,Central,Minnesota,St. Paul,Consumer,Debit Card,69.99,Online,False,4
12,1013,C011,Kate Wilson,Tablet 10inch,Electronics,Mobile,1,399.99,399.99,15,...,Express,Central,Michigan,Detroit,Corporate,Credit Card,79.99,Online,False,3
159,1160,C143,Neil Goodman,Wardrobe,Furniture,Storage,1,399.99,399.99,18,...,Standard,Central,Missouri,Columbia,Consumer,PayPal,79.99,Store,False,4
29,1030,C026,Zack Wright,Sofa,Furniture,Seating,1,599.99,599.99,15,...,Standard,Central,Missouri,Kansas City,Consumer,Debit Card,119.99,Store,False,4

**aggregation and filtering**

In [ ]:
#total sales by category
df.groupby('category')['total_amount'].sum()

category
Electronics        13193.80
Furniture          12319.25
Office Supplies     3211.74
Name: total_amount, dtype: float64

In [ ]:
#average order value by region
df.groupby('region')['total_amount'].mean().round(2)

region
Central    129.964681
East       153.879231
South      151.536939
West       138.258077
Name: total_amount, dtype: float64

In [ ]:
#count of orders by customer agent
df.groupby('customer_segment').value_counts()

customer_segment
Consumer       108
Corporate       32
Home Office     60
Name: order_id, dtype: int64

In [12]:
#total profit by product category
df.groupby('category')['profit'].sum().sort_values(ascending=False)

category
Electronics        2638.20
Furniture          2448.46
Office Supplies     651.54
Name: profit, dtype: float64

In [ ]:
#top 5 customers by total spending
df.groupby('customer_name')['total_amount'].sum().nlargest(5)

customer_name
Henry Taylor      1719.93
Alice Williams    1121.82
Bob Johnson        871.84
Tina Walker        799.99
Emma Davis         704.94
Name: total_amount, dtype: float64

In [ ]:
#average discount by category
df.groupby('category')['discount_percent'].mean()

category
Electronics        10.227848
Furniture          11.277778
Office Supplies     1.805970
Name: discount_percent, dtype: float64

In [ ]:
#sales by payment method
df.groupby('payment_method')['total_amount'].sum()

payment_method
Credit Card    13242.11
Debit Card      6594.79
PayPal          8887.89
Name: total_amount, dtype: float64

**profit vs unprofit**

In [13]:
#profitable vs unprofitable products
res = df.nlargest(10, 'profit')[["product_name","category","profit","total_amount"]]
print(res)

         product_name     category  profit  total_amount
0              Laptop  Electronics  179.99        899.99
22   Conference Table    Furniture  159.99        799.99
8          Smartphone  Electronics  139.99        699.99
101    Reception Desk    Furniture  139.99        699.99
29               Sofa    Furniture  119.99        599.99
103      Drone Camera  Electronics  119.99        599.99
40          Projector  Electronics   99.99        499.99
72      L-Shaped Desk    Furniture   99.99        499.99
3       Standing Desk    Furniture   89.99        449.99
60     Monitor 32inch  Electronics   89.99        449.99

In [14]:
#region wise category performance
df.groupby(['region', 'category'])['total_amount'].sum().unstack(fill_value=0)

category  Electronics  Furniture  Office Supplies
region
Central       1757.75    3479.76           870.83
East          5394.67    2134.78           472.27
South         3249.77    3074.86          1100.68
West          2791.61    3629.85           767.96

In [16]:
#corporate customers with high value orders
res = df[(df['customer_segment']=='Corporate') & (df['total_amount']>200)]

In [ ]:
#monthly sales trend
df['month'] = pd.to_datetime(df['order_date']).dt.month
df.groupby('month')['total_amount'].sum()

month
1    4359.60
2    4557.18
3    3810.08
4    4711.06
5    4532.17
6    3201.79
7    3432.94
8     119.97
Name: total_amount, dtype: float64

In [ ]:
#products with high quantity but low value
df.nlargest(10, ['quantity', 'total_amount'])

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,state,city,customer_segment,payment_method,profit,sales_channel,returned,shipping_duration,profit_category,month
73,1074,C064,Mark Sanders,Envelopes,Office Supplies,Paper,20,2.99,59.80,0,...,North Carolina,Raleigh,Home Office,PayPal,11.96,Store,False,3 days,profitable,3
141,1142,C127,Xena Lowe,Staples,Office Supplies,Organizers,16,1.99,31.84,0,...,Arizona,Chandler,Home Office,PayPal,6.36,Store,False,3 days,profitable,6
61,1062,C053,Bella Cox,Sticky Notes,Office Supplies,Paper,15,3.99,59.85,0,...,Illinois,Springfield,Consumer,Credit Card,11.97,Store,False,3 days,profitable,3
102,1103,C091,Nate Ford,Rubber Bands,Office Supplies,Organizers,15,1.99,29.85,0,...,Kansas,Overland Park,Home Office,Debit Card,5.97,Store,False,3 days,profitable,4
138,1139,C124,Ulysses Horn,Glue Sticks,Office Supplies,Accessories,14,2.99,41.86,0,...,Wisconsin,Kenosha,Home Office,PayPal,8.37,Store,False,3 days,profitable,6
194,1195,C175,Tara Moon,Sticky Tabs,Office Supplies,Organizers,14,2.99,41.86,0,...,Washington,Renton,Home Office,Debit Card,8.37,Store,False,3 days,profitable,7
160,1161,C144,Orla Prince,Tacks,Office Supplies,Organizers,13,2.99,38.87,0,...,North Carolina,Winston-Salem,Home Office,Credit Card,7.77,Store,False,3 days,profitable,6
27,1028,C024,Xavier Allen,Folders,Office Supplies,Organizers,12,3.99,47.88,0,...,Louisiana,New Orleans,Home Office,PayPal,9.57,Store,False,3 days,profitable,2
96,1097,C086,Iris Russell,Binder Clips,Office Supplies,Organizers,12,2.99,35.88,0,...,Arkansas,Fort Smith,Home Office,Debit Card,7.17,Store,False,3 days,profitable,4
197,1198,C178,Wade Hull,Memo Pads,Office Supplies,Paper,12,2.99,35.88,0,...,Wisconsin,Appleton,Home Office,Debit Card,7.17,Store,False,3 days,profitable,7

In [ ]:
#best performing sales chanels by region
df.groupby(['region', 'sales_channel'])['total_amount'].sum()

region   sales_channel
Central  Online           2597.70
         Store            3510.64
East     Online           5104.69
         Store            2897.03
South    Online           3779.75
         Store            3645.56
West     Online           3047.51
         Store            4141.91
Name: total_amount, dtype: float64

In [ ]:
#corporate customers high value orders
df.loc[(df['customer_segment']=='Corporate') & (df['total_amount']>500)]

,order_id,customer_id,customer_name,product_name,category,sub_category,quantity,unit_price,total_amount,discount_percent,...,state,city,customer_segment,payment_method,profit,sales_channel,returned,shipping_duration,profit_category,month
22,1023,C020,Tina Walker,Conference Table,Furniture,Tables,1,799.99,799.99,20,...,Tennessee,Nashville,Corporate,Credit Card,159.99,Store,False,4 days,profitable,2
101,1102,C090,Mona Myers,Reception Desk,Furniture,Desks,1,699.99,699.99,20,...,Washington,Tacoma,Corporate,PayPal,139.99,Store,False,5 days,profitable,4

In [17]:
#profit margin analysis
df['profit_margin'] = (df['profit'] / df['total_amount'] * 100).round(2)
# df.head()

In [19]:
#customer frequency analysis
customer_frequency = df['customer_name'].value_counts()
frequent_customers = customer_frequency[customer_frequency > 3]
print(frequent_customers)

customer_name
Bob Johnson       6
Emma Davis        6
Henry Taylor      6
Alice Williams    4
Name: count, dtype: int64